### ISSUE TITLE
Unable to subscribe with different topics on the same MQTTClient

### ISSUE THREAD

**Issue by MikeMillerDevices** [ChrisPulman/MQTTnet.Rx#72]
Looks like the code should be able to do this however the line
`if (!EqualityComparer<(string topic, int count)>.Default.Equals(check, default))`
doesn't have an else to add a new topic

**Comment by ChrisPulman** [comment]
Thank you for raising this, I will check and update if required.

**Comment by ChrisPulman** [comment]
Version 2.2.0 has been released please let me know if this resolves the issue, thank you for raising this.

**Comment by ChrisPulman** [comment]
@MikeMillerDevices  Please use V2.2.1, V2.2.0 had a version of the MqttNet base that had some issues, hopefully the issue is resolved now

**Comment by bzuu-ic** [comment]
@ChrisPulman it seems the new 2.2.1 version has an incorrect dependency. It [lists](https://www.nuget.org/packages/MQTTnet.Rx.Client/2.2.1#dependencies-body-tab) (>= 4.3.7.1208) for MQTTnet.Extensions.ManagedClient, however the [latest version](https://www.nuget.org/packages/MQTTnet.Extensions.ManagedClient/#versions-body-tab) of this package is 4.3.7.1207 at this point in time.

**Comment by MikeMillerDevices** [comment]
I see the same problem

**Comment by ChrisPulman** [comment]
Thank you, I will investigate why this is occurring and fix it

**Comment by ChrisPulman** [comment]
I am sorry I accidentally added MyGet while testing with V5 of MQTTNet, this should be resolved now

**Comment by MikeMillerDevices** [comment]
Working now thanks
