### ISSUE TITLE
Subscribing with 2 consecutive wildcards doesn't work

### ISSUE THREAD

**Issue by mikewindlake** [ChrisPulman/MQTTnet.Rx#87]
I've tried to subscribe to something like foo/+/+/bar where the topic published is foo/1/2/bar. This wildcarded subscription is valid and works fine in MQTTX.

If I have single wildcard it works fine. 

I haven't found where you're sorting out the topics but just a FYI Mqttnet has a topic matching function which I've used which handles wildcards

**Comment by ChrisPulman** [comment]
Thank you Mike, I will sort this out at the weekend, I am away for work until Friday, I will check out the function in the MqttNet repo.

**Comment by ChrisPulman** [comment]
@mikewindlake I just released V2.3.0 this should solve this, thank you for your feedback, sorry it took longer than hoped to get done, I was away with work longer than expected.

**Comment by mikewindlake** [comment]
Thanks for the update, I haven't had a chance yet to test this but if I find anything else I'll let you know
